INSERT INTO knowledge_guides (title, slug, category, icon, difficulty, tags, content) VALUES
(
  'Context Engineering for LLMs',
  'context-engineering',
  'ai-tools',
  '🧩',
  'intermediate',
  ARRAY['context-engineering', 'rag', 'prompts', 'llm'],
  E'# Context Engineering for LLMs\n\nContext engineering is the discipline of **designing the optimal information environment** for an LLM to produce the best possible output. It goes beyond prompt engineering to encompass the entire pipeline of what gets fed into a model''s context window.\n\n## Why Context Engineering Matters\n\nThe quality of an LLM''s output is directly proportional to the quality of its context. A perfectly-tuned model with poor context will underperform a base model with excellent context.\n\n## Key Pillars\n\n### 1. System Prompt Design\n- Role definition and behavioral constraints\n- Output format specifications\n- Few-shot examples within the system prompt\n- Guardrails and safety instructions\n\n### 2. RAG Pipeline Optimization\n- **Chunking strategies**: semantic vs fixed-size vs recursive\n- **Embedding model selection**: OpenAI, Cohere, BGE, E5\n- **Retrieval tuning**: hybrid search (BM25 + vector), reranking\n- **Context window packing**: fitting the most relevant info in limited tokens\n\n### 3. Tool & Function Output Design\n- Structuring tool responses for LLM consumption\n- MCP (Model Context Protocol) for standardized tool integration\n- Reducing noise in API responses before injecting into context\n\n### 4. Memory & Conversation Management\n- Sliding window vs summarization strategies\n- Long-term memory stores (vector DBs, knowledge graphs)\n- Session state management for multi-turn conversations\n\n## Best Practices\n\n1. **Measure context quality** — track retrieval precision/recall\n2. **Minimize noise** — every irrelevant token costs attention\n3. **Order matters** — place critical info at the start and end (primacy/recency effects)\n4. **Version your contexts** — treat prompts and context templates as code\n5. **Test with evals** — use automated evaluation to measure context impact\n\n## Tools for Context Engineering\n\n| Tool | Purpose |\n|------|---------|\n| LangSmith | Tracing, debugging, evaluation |\n| Braintrust | LLM evals and logging |\n| Weights & Biases | Experiment tracking |\n| Pinecone / Weaviate | Vector search for RAG |\n| Cohere Rerank | Re-ranking retrieved chunks |\n\n## Further Reading\n- Anthropic: Building effective agents\n- OpenAI: Prompt engineering guide\n- LangChain: RAG best practices'
),
(
  'AI Evals & Testing Harness Guide',
  'ai-evals-harness',
  'ai-tools',
  '🧪',
  'intermediate',
  ARRAY['evals', 'testing', 'harness', 'benchmarks'],
  E'# AI Evals & Testing Harness Guide\n\nEvaluation (evals) is the **most important and most underinvested** part of building with LLMs. A testing harness provides the framework to systematically measure model quality, catch regressions, and compare approaches.\n\n## Why Evals Matter\n\n- Models change (new versions, fine-tuning) — you need to know if quality improved or regressed\n- Prompts are fragile — small changes can have large effects\n- Production failures are expensive — catch them before users do\n\n## Types of Evals\n\n### 1. Unit Evals\nTest individual capabilities in isolation:\n- Does the model extract the correct entity?\n- Does it follow the output format?\n- Does it refuse unsafe requests?\n\n### 2. Integration Evals\nTest the full pipeline (RAG + prompt + model):\n- End-to-end accuracy on real queries\n- Latency and cost benchmarks\n- Tool-use correctness\n\n### 3. Red Teaming\nAdversarial testing:\n- Jailbreak attempts\n- Prompt injection attacks\n- Edge cases and boundary conditions\n\n## Building a Harness\n\n### Key Components\n1. **Test dataset** — curated inputs with expected outputs\n2. **Judge function** — LLM-as-judge, exact match, or human review\n3. **Scoring metrics** — accuracy, F1, BLEU, custom rubrics\n4. **Regression tracking** — compare across model versions and prompt changes\n\n## Eval Frameworks\n\n| Framework | Maintainer | Key Feature |\n|-----------|-----------|-------------|\n| Inspect AI | UK AISI | Python-native, flexible |\n| Braintrust | Braintrust | Logging + evals + tracing |\n| Promptfoo | Open Source | CLI-first, CI/CD friendly |\n| DeepEval | Open Source | Unit test style |\n| HELM | Stanford | Comprehensive benchmarks |\n\n## Best Practices\n\n1. **Start with evals before building** — define success criteria first\n2. **Use LLM-as-judge carefully** — calibrate against human ratings\n3. **Run evals in CI/CD** — every prompt change triggers eval suite\n4. **Track metrics over time** — dashboards for quality trends\n5. **Test adversarially** — assume users will try to break it'
),
(
  'Vibe Coding — Building with AI Conversation',
  'vibe-coding',
  'ai-tools',
  '🎨',
  'beginner',
  ARRAY['vibe-coding', 'ai-coding', 'no-code', 'v0', 'bolt'],
  E'# Vibe Coding — Building Apps with AI\n\nVibe coding is the practice of **building software primarily through natural language conversation** with AI tools. Instead of writing code line by line, you describe what you want and let the AI generate, iterate, and refine it.\n\n## The Vibe Coding Stack\n\n### Prompt-to-UI Tools\n- **v0 (Vercel)** — generates React/Next.js UI from text descriptions\n- **bolt.new (StackBlitz)** — full-stack apps from prompts in the browser\n- **Lovable** — AI app builder with deployment\n- **Replit Agent** — builds and deploys apps conversationally\n\n### AI Code Editors\n- **Cursor** — VS Code fork with deep AI integration\n- **Windsurf (Codeium)** — AI-native editor with Cascade flows\n- **GitHub Copilot Agent Mode** — multi-file editing inside VS Code\n\n### Terminal Agents\n- **Claude Code** — Anthropic''s CLI agent\n- **OpenCode** — open-source terminal AI\n- **Codex CLI** — OpenAI''s terminal agent\n\n## How to Vibe Code Effectively\n\n### 1. Start with Clear Descriptions\nBe specific about your tech stack, design system, and expected behavior.\n\n### 2. Iterate Incrementally\n- Don''t try to describe the entire app at once\n- Build feature by feature\n- Review generated code before moving on\n\n### 3. Know When to Hand-Code\nVibe coding works great for UI layouts, CRUD operations, boilerplate, and prototypes.\nYou may still want manual control for complex algorithms, performance-critical paths, and security.\n\n## Tips for Success\n\n1. **Be specific about tech stack** — \"React + Tailwind + TypeScript\" not just \"a web app\"\n2. **Provide visual references** — screenshots, Figma links, similar apps\n3. **Use version control** — commit working states before big changes\n4. **Review the code** — understand what was generated\n5. **Learn the fundamentals** — vibe coding amplifies skill, it doesn''t replace it'
),
(
  'Agentic Design Patterns',
  'agentic-patterns',
  'ai-tools',
  '🔄',
  'intermediate',
  ARRAY['agents', 'agentic', 'patterns', 'tool-use', 'multi-agent'],
  E'# Agentic Design Patterns\n\nAgentic AI refers to systems where an LLM **autonomously plans, executes, and iterates** on tasks using tools, memory, and reasoning loops. Understanding the core patterns helps you build more reliable agents.\n\n## Core Patterns\n\n### 1. ReAct (Reasoning + Acting)\nThe model alternates between **thinking** and **acting** — it reasons about what to do, takes an action, observes the result, and continues.\n\n### 2. Plan & Execute\nSeparate planning from execution:\n1. **Planner** creates a step-by-step plan\n2. **Executor** runs each step\n3. **Replanner** adjusts if steps fail\n\n### 3. Tool Use\nGive the model access to external tools:\n- **Code execution** — run Python, shell commands\n- **API calls** — search, databases, external services\n- **File operations** — read, write, edit files\n- **MCP servers** — standardized tool protocol\n\n### 4. Reflection\nThe model critiques its own output, self-evaluates against criteria, and revises iteratively.\n\n### 5. Multi-Agent Orchestration\nMultiple specialized agents collaborate:\n- **Router** — directs tasks to the right agent\n- **Researcher** — gathers information\n- **Coder** — writes and tests code\n- **Reviewer** — validates output quality\n\n## Frameworks\n\n| Framework | Language | Strengths |\n|-----------|----------|----------|\n| LangGraph | Python/JS | Stateful, graph-based workflows |\n| CrewAI | Python | Role-based multi-agent |\n| AutoGen | Python | Microsoft, conversational agents |\n| Semantic Kernel | C#/Python | Enterprise, Microsoft ecosystem |\n| Mastra | TypeScript | Type-safe agent framework |\n\n## Best Practices\n\n1. **Start simple** — single agent with tools before multi-agent\n2. **Limit tool count** — too many tools confuse the model\n3. **Add guardrails** — validate tool inputs and outputs\n4. **Implement timeouts** — prevent infinite loops\n5. **Log everything** — tracing is essential for debugging\n6. **Human-in-the-loop** — keep humans in the loop for high-stakes decisions'
),
(
  'AI Safety, Guardrails & Red Teaming',
  'ai-safety-guardrails',
  'ai-tools',
  '🛡️',
  'intermediate',
  ARRAY['safety', 'guardrails', 'red-teaming', 'alignment', 'rlhf'],
  E'# AI Safety, Guardrails & Red Teaming\n\nAs AI becomes deeply embedded in applications, ensuring **safe, reliable, and aligned** behavior is critical. This guide covers practical approaches to AI safety for developers.\n\n## Guardrails\n\nGuardrails are **runtime checks** that validate LLM inputs and outputs.\n\n### Input Guardrails\n- **Prompt injection detection** — catch attempts to override system prompts\n- **PII filtering** — redact sensitive data before sending to the model\n- **Topic restriction** — block off-topic or inappropriate requests\n- **Rate limiting** — prevent abuse\n\n### Output Guardrails\n- **Content filtering** — block harmful, biased, or inappropriate content\n- **Hallucination detection** — verify factual claims against sources\n- **Format validation** — ensure structured output matches schema\n- **Toxicity scoring** — measure and filter toxic language\n\n### Tools\n\n| Tool | Purpose |\n|------|---------|\n| Guardrails AI | Python framework for LLM validation |\n| NeMo Guardrails | NVIDIA''s programmable guardrails |\n| Lakera Guard | Prompt injection detection API |\n| Llama Guard | Meta''s safety classifier model |\n\n## Red Teaming\n\nRed teaming is **adversarial testing** of AI systems to find vulnerabilities.\n\n### Common Attack Vectors\n1. **Prompt injection** — overriding system instructions\n2. **Jailbreaking** — bypassing safety filters\n3. **Data extraction** — leaking training data or system prompts\n4. **Indirect injection** — malicious content in retrieved documents\n5. **Goal hijacking** — redirecting agent behavior\n\n## RLHF & Alignment\n\n**Reinforcement Learning from Human Feedback** is how models learn to be helpful, harmless, and honest:\n1. Collect human preference data\n2. Train a reward model\n3. Optimize policy with PPO/DPO\n4. Constitutional AI — self-improvement via principles\n\n## Best Practices\n\n1. **Defense in depth** — layer multiple guardrails\n2. **Assume adversarial users** — never trust user input\n3. **Least privilege** — minimize model access to tools and data\n4. **Monitor production** — log and alert on safety violations\n5. **Stay updated** — follow OWASP LLM Top 10\n6. **Test regularly** — automated red teaming in CI/CD'
);
